### ISSUE TITLE
possible indent issue in hdnet.Data

### ISSUE THREAD

**Issue by LGro** [team-hdnet/hdnet#1]
Could it be that the method `bin_spike_times_trials` has to be indented to belong to the class `Binner`?

https://github.com/team-hdnet/hdnet/blob/a762f0170a73a5a5697cd88e6bc5033425f69d00/hdnet/data.py#L575

**Comment by exilef** [comment]
Definitely, thanks for noticing, Lukas! Fixed as of 535ff0599a987620d3d5a83d3a3e79427cfb6a4a
